config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root '{{page name}}' to set root page
  root 'pages#index'

  resources :users
  resources :discipleship_communities
  resources :small_groups
  resources :events
  resources :assignments
  resources :user_roles

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get "/register", to: 'users#new'
end

app/models/user_role.rb
# frozen_string_literal: true

class UserRole < ApplicationRecord
  belongs_to :small_group, optional: true
  belongs_to :user

  validates :type, presence: true

  self.inheritance_column = nil

  enum type: {
    discipleship_community_pastor: 'discipleship_community_pastor',
    small_group_leader: 'small_group_leader',
    small_group_coordinator: 'small_group_coordinator',
    discipleship_community_coordinator: 'discipleship_community_coordinator',
    small_group_member: 'small_group_member'
  }
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  before_action :admin_user
  before_action :set_user_role, only: [:show, :edit, :update, :destroy]

  # GET /user_roles
  # GET /user_roles.json
  def index
    @user_roles = UserRole.all
  end

  # GET /user_roles/1
  # GET /user_roles/1.json
  def show
  end

  # GET /user_roles/new
  def new
    @user_role = UserRole.new
  end

  # GET /user_roles/1/edit
  def edit
  end

  # POST /user_roles
  # POST /user_roles.json
  def create
    @user_role = UserRole.new(user_role_params)

    respond_to do |format|
      if @user_role.save
        format.html { redirect_to @user_role, notice: 'User role was successfully created.' }
        format.json { render :show, status: :created, location: @user_role }
      else
        format.html { render :new }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_roles/1
  # PATCH/PUT /user_roles/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        format.html { redirect_to @user_role, notice: 'User role was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_roles/1
  # DELETE /user_roles/1.json
  def destroy
    @user_role.destroy
    respond_to do |format|
      format.html { redirect_to user_roles_url, notice: 'User role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_role_params
      params.require(:user_role).permit(:user, :role, :group)
    end
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/user_roles/_form.html.erb
<%= form_with(model: user_role, local: true) do |form| %>
  <% if user_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_role.errors.count, "error") %> prohibited this user_role from being saved:</h2>

      <ul>
        <% user_role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.number_field :user %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.number_field :role %>
  </div>

  <div class="field">
    <%= form.label :group %>
    <%= form.number_field :group %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_roles/edit.html.erb
<h1>Editing User Role</h1>

<%= render 'form', user_role: @user_role %>

<%= link_to 'Show', @user_role %> |
<%= link_to 'Back', user_roles_path %>

app/views/user_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Roles</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Role</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_roles.each do |user_role| %>
      <tr>
        <td><%= user_role.id %></td>
        <td><%= link_to user_role.user.name, user_path(user_role.id) %></td>
        <td><%= user_role.type.humanize %></td>
        <td>
          <% if user_role.small_group %>
            <%= user_role.small_group.leader.name + ' - ' + user_role.small_group.discipleship_community.night %>
          <% else %>
            N/A
          <% end %>
        </td>
        <td><%= link_to 'Show', user_role %></td>
        <td><%= link_to 'Edit', edit_user_role_path(user_role) %></td>
        <td><%= link_to 'Destroy', user_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Role', new_user_role_path %>

app/views/user_roles/new.html.erb
<h1>New User Role</h1>

<%= render 'form', user_role: @user_role %>

<%= link_to 'Back', user_roles_path %>

app/views/user_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_role.user %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user_role.role %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user_role.group %>
</p>

<%= link_to 'Edit', edit_user_role_path(@user_role) %> |
<%= link_to 'Back', user_roles_path %>