config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root '{{page name}}' to set root page
  root 'pages#index'

  resources :users
  resources :discipleship_communities
  resources :small_groups
  resources :events
  resources :assignments
  resources :user_roles

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get "/register", to: 'users#new'
end

app/models/small_group.rb
# frozen_string_literal: true

class SmallGroup < ApplicationRecord
  belongs_to :discipleship_community
  belongs_to :leader, class_name: 'User'
  has_many :user_roles
  has_many :events, as: :gatherable

  # returns group night
  def night
    discipleship_community.night
  end

  # returns the group's coordinator
  def coordinator
    User.where(user_roles: UserRole.where(small_group_id: id, type: :small_group_coordinator))[0]
  end

  # returns the members of the small group
  def members
    User.where(user_roles: user_roles)
  end

  # returns a list of members sorted by user role
  def sortedMembers
    rest = []
    members = User.where(user_roles: user_roles).order(:first_name)
    members.each do |member|
      if member.user_roles.where(small_group_id: id) == UserRole.types[:small_group_leader]
        leader = member
      elsif member.user_roles.where(small_group_id: id) == UserRole.types[:small_group_coordinator]
        coordinator = member
      else
        rest << member
      end
    end
    [leader, coordinator, rest].flatten
  end
end

app/controllers/small_groups_controller.rb
# frozen_string_literal: true

class SmallGroupsController < ApplicationController
  before_action :admin_user
  before_action :set_small_group, only: %i[show edit update destroy]

  # GET /small_groups
  # GET /small_groups.json
  def index
    night = if request.params['night'] && helpers.is_day_of_the_week?(request.params['night'])
              request.params['night'].to_date
            else
              ''
            end
    @active_nights = helpers.get_active_nights
    if night.is_a? Date
      @dcs = DiscipleshipCommunity.where('night = ?', DiscipleshipCommunity.nights[night.strftime('%A').downcase])
    else
      @dcs = DiscipleshipCommunity.all
    end

    if night.is_a? Date
      dcs = DiscipleshipCommunity.select(:id).where('night = ?', DiscipleshipCommunity.nights[night.strftime('%A').downcase])
      dc_ids = []
      dcs.each { |dc| dc_ids << dc.id }
      @small_groups = SmallGroup.where(discipleship_community_id: dc_ids)
    else
      @small_groups = SmallGroup.all
    end

    @night = night
  end

  # GET /small_groups/1
  # GET /small_groups/1.json
  def show; end

  # GET /small_groups/new
  def new
    @small_group = SmallGroup.new
  end

  # GET /small_groups/1/edit
  def edit; end

  # POST /small_groups
  # POST /small_groups.json
  def create
    @small_group = SmallGroup.new(small_group_params)

    respond_to do |format|
      if @small_group.save
        format.html { redirect_to @small_group, notice: 'Small group was successfully created.' }
        format.json { render :show, status: :created, location: @small_group }
      else
        format.html { render :new }
        format.json { render json: @small_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /small_groups/1
  # PATCH/PUT /small_groups/1.json
  def update
    respond_to do |format|
      if @small_group.update(small_group_params)
        format.html { redirect_to @small_group, notice: 'Small group was successfully updated.' }
        format.json { render :show, status: :ok, location: @small_group }
      else
        format.html { render :edit }
        format.json { render json: @small_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /small_groups/1
  # DELETE /small_groups/1.json
  def destroy
    @small_group.destroy
    respond_to do |format|
      format.html { redirect_to small_groups_url, notice: 'Small group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_small_group
    @small_group = SmallGroup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def small_group_params
    params.require(:small_group).permit(:user_role_id, :discipleship_community_id)
  end
end

app/helpers/small_groups_helper.rb
# frozen_string_literal: true

module SmallGroupsHelper
  # returns the abbreviated version of an array of days of the week
  def abbr_nights(nights)
    nights.map(&:to_date)
  end

  # returns an array of nights where there is a discipleship community
  def get_active_nights
    active_nights = DiscipleshipCommunity.nights.keys.filter do |n|
      DiscipleshipCommunity
        .where(night: DiscipleshipCommunity.nights[n])
        .count
        .positive?
    end
    abbr_nights(active_nights)
  end

  def is_day_of_the_week?(day)
    (Date::DAYNAMES.include?(day.capitalize) || \
    Date::ABBR_DAYNAMES.include?(day.capitalize))
  end
end

app/views/small_groups/_form.html.erb
<%= form_with(model: @small_group, local: true) do |form| %>
  <% if small_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(small_group.errors.count, "error") %> prohibited this small_group from being saved:</h2>

      <ul>
        <% small_group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :leader_id %>
    <%= form.collection_select(:leader_id, User.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :pastor_id %>
    <%= form.collection_select(:pastor_id , User.where(user_roles: UserRole.where(type: :discipleship_community_pastor)), :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :coordinator_id %>
    <%= form.collection_select(:coordinator_id , @small_group.members, :id, :name) %>
  </div>
  <% if @small_group.members.count > 0 %>
    <ul>
      <% @small_group.sortedMembers.each do |member| %>
        <li><%= member.name %></li>
      <% end %>
      <ul>
      <% end %>

      <div class="field">
        <%= form.label :user_role_id %>
        <%= form.number_field :user_role_id %>
      </div>

      <div class="field">
        <%= form.label :discipleship_community_id %>
        <%= form.number_field :discipleship_community_id %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>

app/views/small_groups/edit.html.erb
<h1>Editing Small Group</h1>

<%= render 'form', small_group: @small_group %>

<%= link_to 'Show', @small_group %> |
<%= link_to 'Back', small_groups_path %>

app/views/small_groups/index.html.erb
<% provide(:title, "Small groups") %>
<div class="content-container">

  <p id="notice"><%= notice %></p>

  <% if current_user.admin? %>
    <%= link_to 'New Small Group', new_small_group_path %>
  <% end %>
  <h1 class="page-title">Small Groups</h1>
  <ul class="night-list list">
    <li class="night-list__item">
      <a
          class="night-list__link link <%= @night === '' ? 'night-list__link--active' : '' %>"
          href="/small_groups"
      > All </a>
    </li>
    <% @active_nights.each do |night| %>
      <li class="night-list__item">
        <a
          class="night-list__link link <%= @night.strftime('%a') === night.strftime('%a') ? 'night-list__link--active' : '' if @night.is_a? Date %>"
          href="/small_groups?night=<%= night.strftime('%A').downcase %>"
        >
          <%= night.strftime('%a') %>
        </a>
      </li>
    <% end %>
  </ul>

  <ul class="dc-list">
    <% @dcs.each do |dc| %>
      <li class="dc-list__item dc">
        <div class="dc__summary">
          <img class="user-avatar user-avatar--128 user-avatar--pastor" src="https://source.unsplash.com/collection/8470962/128x128">
          <div class="dc__details">
            <h2 class="dc-pastor__name">
              <%= dc.pastor.name %>
            </h2>
            <h3 class="dc__group-count">
              <%= pluralize(dc.small_groups.count, 'group') %>
            </h3>
          </div>
        </div>
        <div class="divider-line divider-line--dc"></div>
        <ul class="user-list">
          <% dc.small_groups.each do |group| %>
            <li class="user-list__item">
              <a class="user-list__link link" href="<%= small_group_path(group) %>">
                <img class="user__avatar user-avatar user-avatar--48" src="https://source.unsplash.com/collection/8470962/48x48">
                <h4 class="user__name user__name--small">
                  <%= group.leader.name %>
                </h4>
              </a>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/small_groups/new.html.erb
<h1>New Small Group</h1>

<%= render 'form', small_group: @small_group %>

<%= link_to 'Back', small_groups_path %>

app/views/small_groups/show.html.erb
<% provide(:title, @small_group.leader.name + "'s Small Group") %>
<div class="content-container">

  <p id="notice"><%= notice %></p>

    <a href="<%= small_groups_path %>" class="link link--back link"><i class="link__icon--12 fas fa-chevron-left"></i> Small Groups</a>

  <div class="gatherable-grid">
    <div class="group__summary">
      <img class="user-avatar user-avatar--128 user-avatar--group-leader" src="https://source.unsplash.com/collection/8470962/128x128">
      <div class="group__details">
        <h1 class="group__leader-name group__leader-name--large"><%= @small_group.leader.name %></h1>
        <div class="group__info-groups">
          <div class="group__info-group">
            <i class="group__details-icon far fa-calendar-alt"></i>
            <div>
              Meets on <a class="group__night link" href="/small_groups?night=<%= @small_group.discipleship_community.night %>"><%= @small_group.discipleship_community.night.capitalize %></a> night
            </div>
          </div>
          <div class="group__info-group">
            <i class="group__details-icon fas fa-users"></i>
            <div>
              In <a class="group__dc link" href="#"><%= @small_group.discipleship_community.pastor.name %></a> Discipleship Community
            </div>
          </div>
        </div>
        <% if current_user.admin? %>
          <a class="link link--edit" href="<%= edit_small_group_path(@small_group) %>"><i class="link__icon--8 fas fa-pencil-alt"></i>Edit small group</a>
        <% end %>
      </div>
    </div>

    <div class="group-members">
      <div class="group-members__text">
        <h2 class="section-title inline"><%= pluralize(@small_group.user_roles.count, 'members') %></h2>
        <button class="group__list-toggle button">
          <span>Show details</span><i class="group__list-toggle-icon fas fa-chevron-down"></i>
        </button>
      </div>
      <div class="divider-line"></div>
      <div class="group__members-list">
        <ul class="user-list collapsed">
          <% @small_group.user_roles.order(:type).each do |member| %>
            <li class="user-list__item">
              <a class="user-list__link link" href="<%= user_path(member) %>">
                <img class="user__avatar user-avatar user-avatar--48" src="https://source.unsplash.com/collection/8470962/48x48">
                <div class="user__details">
                  <h4 class="user__name user__name--small">
                      <%= member.user.name %>
                  </h4>
                  <% if member.type === UserRole.types[:small_group_leader] || member.type === UserRole.types[:small_group_coordinator] %>
                  <div class="user__role user__role--<%= member.type.dasherize %> badge"><%= member.type.humanize %></div>
                  <% end %>
                </div>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="events">
      <h2 class="section-title inline"><%= pluralize(3, 'upcoming event') %></h2>
      <div class="divider-line"></div>
      <ul class="events__list">
        <li class="event-card event-card--small">
          <a href="#" class="event-card__link link">
            <div class="event-card__date-group">
              <div class="event-card__gradient-line"></div>
              <div class="event-card__date">17</div>
              <div class="event-card__month">Dec</div>
            </div>
            <div class="event-card__details-group">
              <div class="event-card__event-name">White Elephant Party</div>
              <div class="event-card__reminder badge badge--small">On snack</div>
              <div class="event-card__time">7:00PM - 9:00PM</div>
            </div>
          </a>
        </li>
        <li class="event-card event-card--small">
          <a href="#" class="event-card__link link">
            <div class="event-card__date-group">
              <div class="event-card__gradient-line"></div>
              <div class="event-card__date">21</div>
              <div class="event-card__month">Dec</div>
            </div>
            <div class="event-card__details-group">
              <div class="event-card__event-name">Discipleship Community Christmas Party</div>
              <div class="event-card__time">1:00PM - 3:30PM</div>
            </div>
          </a>
        </li>
        <li class="event-card event-card--small">
          <a href="#" class="event-card__link link">
            <div class="event-card__date-group">
              <div class="event-card__gradient-line"></div>
              <div class="event-card__date">25</div>
              <div class="event-card__month">Dec</div>
            </div>
            <div class="event-card__details-group">
              <div class="event-card__event-name">Christmas 🎄🎁</div>
            </div>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>